/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_saschahlusiak_freebloks_controller_JNIServer */

#ifndef _Included_de_saschahlusiak_freebloks_controller_JNIServer
#define _Included_de_saschahlusiak_freebloks_controller_JNIServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_saschahlusiak_freebloks_controller_JNIServer
 * Method:    native_run_server
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_saschahlusiak_freebloks_controller_JNIServer_native_1run_1server
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_saschahlusiak_freebloks_controller_JNIServer
 * Method:    native_resume_server
 * Signature: (III[I[II)I
 */
JNIEXPORT jint JNICALL Java_de_saschahlusiak_freebloks_controller_JNIServer_native_1resume_1server
  (JNIEnv *, jclass, jint, jint, jint, jintArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
